default_install_hook_types:
  - pre-commit
  - commit-msg

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        stages: [pre-commit]
      - id: check-added-large-files
        stages: [pre-commit]
      - id: check-ast
        stages: [pre-commit]
      - id: check-case-conflict
        stages: [pre-commit]
      - id: check-json
        stages: [pre-commit]
      - id: check-toml
        stages: [pre-commit]
      - id: check-yaml
        stages: [pre-commit]
      - id: end-of-file-fixer
        stages: [pre-commit]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.12
    hooks:
      - id: ruff-check # linter
        args: [--fix]
        stages: [pre-commit]
      - id: ruff-format # formatter
        stages: [pre-commit]
  - repo: local
    hooks:
      - id: pyright
        name: pyright
        entry: uv run pyright
        language: system
        stages: [pre-commit]
        types: [python]
        pass_filenames: false
      - id: commit-message-check
        name: commit message check
        entry: python3 scripts/check_commit_msg.py
        language: system
        stages: [commit-msg]
        pass_filenames: true
